# action.yml
name: "Run n8n workflow"
description: "Run defined n8n workflow"
inputs:
  workflow: # id of input
    description: "ID of the Workflow to run"
    required: true
    default: "1"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.workflow }}
