# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  workflow: # id of input
    description: "Workflow to run"
    required: true
    default: "main.json"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.workflow }}
