on:
  pull_request:
    types: [opened]
jobs:
  run_n8n_workflow:
    runs-on: ubuntu-latest
    name: Run n8n Workflow
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run n8n Workflow
        uses: ./ # Uses an action in the root directory
        id: n8n
        with:
          workflow: "3"
        env: # Or as an environment variable
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
